/**
 * Property-Based Tests for Page Metadata
 * 
 * Tests universal properties of page metadata generation:
 * - Property 18: Page Metadata Completeness
 * 
 * Requirements: 6.1
 */

/**
 * @jest-environment node
 */

import * as fc from 'fast-check';
import { Metadata } from 'next';

// ============================================================================
// Test Data - Sample Metadata from All Pages
// ============================================================================

/**
 * Sample metadata objects representing all pages in the application
 * These are representative examples of the actual metadata exported by pages
 */
const staticPagesMetadata: Array<{ path: string; name: string; metadata: Metadata }> = [
  {
    path: '/',
    name: 'Home',
    metadata: {
      title: 'Home | Colour Clouds Digital',
      description: 'Shaping Digital Experiences, One App at a Time. Innovative app development and digital content creation services from Colour Clouds Digital.',
      alternates: {
        canonical: '/',
      },
      openGraph: {
        title: 'Home | Colour Clouds Digital',
        description: 'Shaping Digital Experiences, One App at a Time. Innovative app development and digital content creation services from Colour Clouds Digital.',
        type: 'website',
        url: '/',
      },
    },
  },
  {
    path: '/services',
    name: 'Services',
    metadata: {
      title: 'Services | Colour Clouds Digital',
      description: 'Professional app development and digital content creation services. We build cutting-edge applications and create compelling digital content that engages your audience.',
      alternates: {
        canonical: '/services',
      },
      openGraph: {
        title: 'Services | Colour Clouds Digital',
        description: 'Professional app development and digital content creation services. We build cutting-edge applications and create compelling digital content that engages your audience.',
        type: 'website',
        url: '/services',
      },
    },
  },
  {
    path: '/about',
    name: 'About',
    metadata: {
      title: 'About Us | Colour Clouds Digital',
      description: 'Learn about Colour Clouds Digital - our story, mission, vision, and values. We are passionate about creating innovative digital solutions that make a difference.',
      alternates: {
        canonical: '/about',
      },
      openGraph: {
        title: 'About Us | Colour Clouds Digital',
        description: 'Learn about Colour Clouds Digital - our story, mission, vision, and values. We are passionate about creating innovative digital solutions that make a difference.',
        type: 'website',
        url: '/about',
      },
    },
  },
  {
    path: '/blog',
    name: 'Blog Listing',
    metadata: {
      title: 'Blog | Colour Clouds Digital',
      description: 'Read our latest articles on app development, digital content creation, and technology insights.',
      alternates: {
        canonical: '/blog',
      },
      openGraph: {
        title: 'Blog | Colour Clouds Digital',
        description: 'Read our latest articles on app development, digital content creation, and technology insights.',
        type: 'website',
        url: '/blog',
      },
    },
  },
  {
    path: '/contact',
    name: 'Contact',
    metadata: {
      title: 'Contact Us | Colour Clouds Digital',
      description: 'Get in touch with Colour Clouds Digital. Send us a message about your project or inquiry. We offer app development and digital content creation services.',
      alternates: {
        canonical: '/contact',
      },
      openGraph: {
        title: 'Contact Us | Colour Clouds Digital',
        description: 'Get in touch with Colour Clouds Digital. Send us a message about your project or inquiry. We offer app development and digital content creation services.',
        type: 'website',
        url: '/contact',
      },
    },
  },
];

/**
 * Sample dynamic blog post metadata
 * Represents metadata generated by generateMetadata() for blog posts
 */
const sampleBlogPostMetadata: Metadata = {
  title: 'Building a Modern Portfolio | Colour Clouds Digital',
  description: 'Learn how to build a modern portfolio website with Next.js, TypeScript, and Tailwind CSS.',
  alternates: {
    canonical: '/blog/building-modern-portfolio',
  },
  openGraph: {
    title: 'Building a Modern Portfolio',
    description: 'Learn how to build a modern portfolio website with Next.js, TypeScript, and Tailwind CSS.',
    images: ['https://example.com/image.jpg'],
    type: 'article',
    publishedTime: '2024-01-15T10:00:00Z',
    authors: ['Jane Smith'],
    url: '/blog/building-modern-portfolio',
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Building a Modern Portfolio',
    description: 'Learn how to build a modern portfolio website with Next.js, TypeScript, and Tailwind CSS.',
    images: ['https://example.com/image.jpg'],
  },
};

/**
 * Fallback metadata for non-existent blog posts
 */
const fallbackBlogPostMetadata: Metadata = {
  title: 'Post Not Found | Colour Clouds Digital',
  description: 'The requested blog post could not be found.',
};

// ============================================================================
// Helper Functions
// ============================================================================

/**
 * Check if metadata has required fields (title and description)
 */
function hasCompleteMetadata(metadata: Metadata | undefined): boolean {
  if (!metadata) return false;
  
  // Check for title
  const hasTitle = typeof metadata.title === 'string' && metadata.title.length > 0;
  
  // Check for description
  const hasDescription = typeof metadata.description === 'string' && metadata.description.length > 0;
  
  return hasTitle && hasDescription;
}

// ============================================================================
// Property 18: Page Metadata Completeness
// ============================================================================

describe('Property 18: Page Metadata Completeness', () => {
  /**
   * **Validates: Requirements 6.1**
   * 
   * Requirement 6.1: THE System SHALL generate dynamic metadata for all pages 
   * including title and description
   * 
   * Property: For all pages in the application (static and dynamic), the metadata 
   * SHALL include both a title and description field with non-empty string values.
   * 
   * This property tests that:
   * 1. Every static page has metadata with title and description
   * 2. Dynamic blog post pages generate metadata with title and description
   * 3. Title is a non-empty string
   * 4. Description is a non-empty string
   * 5. Metadata is properly structured according to Next.js Metadata type
   */

  it('should have complete metadata (title and description) for all static pages', () => {
    // Test each static page
    staticPagesMetadata.forEach(({ path, name, metadata }) => {
      // Property: Metadata must exist
      expect(metadata).toBeDefined();
      expect(metadata).not.toBeNull();
      
      // Property: Metadata must have title
      expect(metadata.title).toBeDefined();
      expect(typeof metadata.title).toBe('string');
      expect((metadata.title as string).length).toBeGreaterThan(0);
      
      // Property: Metadata must have description
      expect(metadata.description).toBeDefined();
      expect(typeof metadata.description).toBe('string');
      expect((metadata.description as string).length).toBeGreaterThan(0);
      
      // Property: Metadata is complete
      expect(hasCompleteMetadata(metadata)).toBe(true);
      
      // Log for debugging
      console.log(`✓ ${name} (${path}): title="${metadata.title}", description="${metadata.description?.substring(0, 50)}..."`);
    });
  });

  it('should have complete metadata for dynamic blog post pages', () => {
    // Test sample blog post metadata
    const metadata = sampleBlogPostMetadata;
    
    // Property: Metadata must exist
    expect(metadata).toBeDefined();
    expect(metadata).not.toBeNull();
    
    // Property: Metadata must have title
    expect(metadata.title).toBeDefined();
    expect(typeof metadata.title).toBe('string');
    expect((metadata.title as string).length).toBeGreaterThan(0);
    
    // Property: Metadata must have description
    expect(metadata.description).toBeDefined();
    expect(typeof metadata.description).toBe('string');
    expect((metadata.description as string).length).toBeGreaterThan(0);
    
    // Property: Metadata is complete
    expect(hasCompleteMetadata(metadata)).toBe(true);
  });

  it('should have title field as a non-empty string for all pages', () => {
    // Test all static pages
    staticPagesMetadata.forEach(({ path, name, metadata }) => {
      // Property: Title must be a string
      expect(typeof metadata.title).toBe('string');
      
      // Property: Title must not be empty
      expect((metadata.title as string).trim().length).toBeGreaterThan(0);
      
      // Property: Title should not be just whitespace
      expect((metadata.title as string).trim()).toBe(metadata.title);
      
      // Property: Title should be reasonable length (not too short, not too long)
      const titleLength = (metadata.title as string).length;
      expect(titleLength).toBeGreaterThanOrEqual(5); // Minimum reasonable title length
      expect(titleLength).toBeLessThanOrEqual(100); // Maximum reasonable title length
    });
  });

  it('should have description field as a non-empty string for all pages', () => {
    // Test all static pages
    staticPagesMetadata.forEach(({ path, name, metadata }) => {
      // Property: Description must be a string
      expect(typeof metadata.description).toBe('string');
      
      // Property: Description must not be empty
      expect((metadata.description as string).trim().length).toBeGreaterThan(0);
      
      // Property: Description should not be just whitespace
      expect((metadata.description as string).trim()).toBe(metadata.description);
      
      // Property: Description should be reasonable length (not too short, not too long)
      const descLength = (metadata.description as string).length;
      expect(descLength).toBeGreaterThanOrEqual(20); // Minimum reasonable description length
      expect(descLength).toBeLessThanOrEqual(300); // Maximum reasonable description length for SEO
    });
  });

  it('should maintain consistent metadata structure across all pages', () => {
    // Property: All pages should have metadata
    staticPagesMetadata.forEach(({ page, metadata }) => {
      expect(metadata).toBeDefined();
      expect(metadata).not.toBeNull();
    });
    
    // Property: All pages should have the same required fields
    staticPagesMetadata.forEach(({ page, metadata }) => {
      expect(metadata).toHaveProperty('title');
      expect(metadata).toHaveProperty('description');
    });
    
    // Property: All titles should be strings
    staticPagesMetadata.forEach(({ page, metadata }) => {
      expect(typeof metadata.title).toBe('string');
    });
    
    // Property: All descriptions should be strings
    staticPagesMetadata.forEach(({ page, metadata }) => {
      expect(typeof metadata.description).toBe('string');
    });
  });

  it('should have metadata that follows Next.js Metadata type structure', () => {
    // Test all static pages
    staticPagesMetadata.forEach(({ path, name, metadata }) => {
      // Property: Metadata should be an object
      expect(typeof metadata).toBe('object');
      expect(metadata).not.toBeNull();
      
      // Property: If alternates exists, it should have canonical
      if (metadata.alternates) {
        expect(metadata.alternates).toHaveProperty('canonical');
        expect(typeof metadata.alternates.canonical).toBe('string');
      }
      
      // Property: If openGraph exists, it should have required fields
      if (metadata.openGraph) {
        expect(metadata.openGraph).toHaveProperty('title');
        expect(metadata.openGraph).toHaveProperty('description');
        expect(typeof metadata.openGraph.title).toBe('string');
        expect(typeof metadata.openGraph.description).toBe('string');
      }
    });
  });

  it('should have proper fallback metadata for non-existent blog posts', () => {
    const metadata = fallbackBlogPostMetadata;
    
    // Property: Fallback metadata should exist
    expect(metadata).toBeDefined();
    expect(metadata).not.toBeNull();
    
    // Property: Fallback metadata should have title
    expect(metadata.title).toBeDefined();
    expect(typeof metadata.title).toBe('string');
    expect((metadata.title as string).length).toBeGreaterThan(0);
    
    // Property: Fallback metadata should have description
    expect(metadata.description).toBeDefined();
    expect(typeof metadata.description).toBe('string');
    expect((metadata.description as string).length).toBeGreaterThan(0);
    
    // Property: Fallback metadata should indicate post not found
    const title = metadata.title as string;
    const description = metadata.description as string;
    expect(
      title.toLowerCase().includes('not found') || 
      description.toLowerCase().includes('not found') ||
      title.toLowerCase().includes('post')
    ).toBe(true);
  });

  it('should have unique titles across different pages', () => {
    const titles = new Set<string>();
    
    // Collect all titles from static pages
    staticPagesMetadata.forEach(({ path, name, metadata }) => {
      const title = metadata.title as string;
      
      // Property: Title should be unique (not already seen)
      expect(titles.has(title)).toBe(false);
      titles.add(title);
    });
    
    // Property: Number of unique titles should equal number of pages
    expect(titles.size).toBe(staticPagesMetadata.length);
  });

  it('should have unique descriptions across different pages', () => {
    const descriptions = new Set<string>();
    
    // Collect all descriptions from static pages
    staticPagesMetadata.forEach(({ path, name, metadata }) => {
      const description = metadata.description as string;
      
      // Property: Description should be unique (not already seen)
      expect(descriptions.has(description)).toBe(false);
      descriptions.add(description);
    });
    
    // Property: Number of unique descriptions should equal number of pages
    expect(descriptions.size).toBe(staticPagesMetadata.length);
  });

  it('should include brand name in page titles', () => {
    const brandName = 'Colour Clouds Digital';
    
    // Test all static pages
    staticPagesMetadata.forEach(({ path, name, metadata }) => {
      const title = metadata.title as string;
      
      // Property: Title should include brand name for SEO consistency
      expect(title).toContain(brandName);
    });
  });

  it('should have metadata fields that are properly trimmed (no leading/trailing whitespace)', () => {
    // Test all static pages
    staticPagesMetadata.forEach(({ path, name, metadata }) => {
      // Property: Title should be trimmed
      const title = metadata.title as string;
      expect(title).toBe(title.trim());
      expect(title).not.toMatch(/^\s/); // No leading whitespace
      expect(title).not.toMatch(/\s$/); // No trailing whitespace
      
      // Property: Description should be trimmed
      const description = metadata.description as string;
      expect(description).toBe(description.trim());
      expect(description).not.toMatch(/^\s/); // No leading whitespace
      expect(description).not.toMatch(/\s$/); // No trailing whitespace
    });
  });

  it('should have descriptions that are complete sentences', () => {
    // Test all static pages
    staticPagesMetadata.forEach(({ path, name, metadata }) => {
      const description = metadata.description as string;
      
      // Property: Description should end with proper punctuation
      expect(description).toMatch(/[.!?]$/);
      
      // Property: Description should start with a capital letter
      expect(description[0]).toMatch(/[A-Z]/);
    });
  });

  it('should maintain metadata completeness invariant across all page types', () => {
    fc.assert(
      fc.property(
        // Generate test cases for different page types
        fc.constantFrom(...staticPagesMetadata),
        (page) => {
          const metadata = page.metadata;
          
          // Property: Metadata completeness invariant
          // For ANY page in the system, metadata MUST have both title and description
          expect(hasCompleteMetadata(metadata)).toBe(true);
          
          // Property: Title and description must be non-empty strings
          expect(typeof metadata.title).toBe('string');
          expect((metadata.title as string).length).toBeGreaterThan(0);
          expect(typeof metadata.description).toBe('string');
          expect((metadata.description as string).length).toBeGreaterThan(0);
        }
      ),
      { numRuns: 50 }
    );
  });

  it('should generate metadata with proper structure for blog posts', () => {
    fc.assert(
      fc.property(
        // Generate various blog post metadata scenarios
        fc.record({
          title: fc.stringMatching(/^[A-Z][a-zA-Z0-9\s\-.,!?']{10,80}$/),
          excerpt: fc.stringMatching(/^[A-Z][a-zA-Z0-9\s\-.,!?']{20,200}$/),
          slug: fc.stringMatching(/^[a-z0-9][a-z0-9-]{1,48}[a-z0-9]$/),
        }),
        ({ title, excerpt, slug }) => {
          // Simulate metadata generation for a blog post
          const metadata: Metadata = {
            title: `${title} | Colour Clouds Digital`,
            description: excerpt,
            alternates: {
              canonical: `/blog/${slug}`,
            },
            openGraph: {
              title,
              description: excerpt,
              type: 'article',
              url: `/blog/${slug}`,
            },
          };
          
          // Property: Generated metadata must be complete
          expect(hasCompleteMetadata(metadata)).toBe(true);
          
          // Property: Title must include brand name
          expect(metadata.title).toContain('Colour Clouds Digital');
          
          // Property: Description must match excerpt
          expect(metadata.description).toBe(excerpt);
          
          // Property: Canonical URL must match slug
          expect(metadata.alternates?.canonical).toBe(`/blog/${slug}`);
          
          // Property: OpenGraph must have required fields
          expect(metadata.openGraph).toHaveProperty('title');
          expect(metadata.openGraph).toHaveProperty('description');
          expect(metadata.openGraph).toHaveProperty('type');
          expect(metadata.openGraph?.type).toBe('article');
        }
      ),
      { numRuns: 100 }
    );
  });
});
